---
# health page
- name: check if ovirt-engine running (health page)
  uri:
    url: "http://{{ ovirt_engine_db_host }}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 2
  delay: 5
  until: ovirt_engine_status is success
  ignore_errors: True

# copy dwh on dwh answer file
# this answerfile results in a 2 VM setup where
# VM 1: holds engine and it's `engine` DB instance
# and VM 2: which holds dwh service and it's `ovirt_engine_history` DB
- name: copy answerfile for `ovirt_engine_history` db to be on dwhservice VM
  template:
    src: answerfile_{{ ovirt_engine_version }}_ovirt_engine_history_db_on_dwhservice_host.txt.j2
    dest: /tmp/answerfile.txt
    mode: 0644
    owner: root
    group: root
  when: ovirt_engine_history_db_on_dwhservice_host == True

# - case where the database of dwh on 3rd machine
- name: copy answerfile for `ovirt_engine_history` db to be on remote VM and not on dwhservice VM
  template:
    src: answerfile_{{ ovirt_engine_version }}_ovirt_engine_history_db_not_on_dwhservice_host.txt.j2
    dest: /tmp/answerfile.txt
    mode: 0644
    owner: root
    group: root
  when: ovirt_engine_history_db_on_dwhservice_host == False

- name: run engine-setup with answerfile
  shell: 'engine-setup --config-append=/tmp/answerfile.txt'
  tags:
    - skip_ansible_lint

- name: check state of database
  service:
    name: postgresql
    state: started
  when: (ovirt_engine_dwh_db_host == 'localhost' and ovirt_engine_dwh == True) or ovirt_engine_db_host == 'localhost'

# health page
- name: check if ovirt-engine running (health page)
  uri:
    url: "http://{{ ovirt_engine_db_host }}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 12
  delay: 5
  until: ovirt_engine_status is success
  ignore_errors: True

- name: Restart `ovirt-engine-dwhd` service
  service:
    name: ovirt-engine-dwhd
    state: restarted

- debug: msg='Restart ovirt-engine on the remote host by doing a `service ovirt-engine restart`'
