---
# grep returns an exit code of 1 when it doesn't match any lines. Ansible then
# interprets this (actually any status code other than 0 from a shell/command
# task) as an error and so promptly fails.
- name: Register the engine name stored inside the files in directory `/etc/ovirt-engine`
  command: grep -R --include \*.conf {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine
  register: grep_output_remote_run
  changed_when: False
  failed_when: "grep_output_remote_run.rc == 2"
  ignore_errors: yes

- name: Saving the above diff result
  copy: content="{{ grep_output_remote_run.stdout }}" dest=/tmp/engine-rename-logs-current.grep
  notify:
    - delete engine-rename engine rename logs

- debug: msg="The command grep -R {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine returned {{ grep_output_remote_run.stdout }}"

- name: Copy the expected result to /tmp on the remote vm to be compared with existing engine-rename logs
  template:
    src: check-engine-name-expected-result.grep.j2
    dest: /tmp/check-engine-name-expected-result.grep
  notify:
    - delete engine-rename expected log files

# if the engine-name is already at the state where we want it to be
- name: Comparing the grep diff for the one that we expect and the one we just ran
  command: diff --ignore-all-space /tmp/check-engine-name-expected-result.grep /tmp/engine-rename-logs-current.grep
  register: grep_diff
  changed_when: False
  failed_when: "grep_diff.rc == 2"
  ignore_errors: yes

- name: Running engine-rename command (if the engine-name diff stdout != "")
  shell: |
    /usr/share/ovirt-engine/setup/bin/ovirt-engine-rename \
    --newname={{ ovirt_engine_rename_new_fqdn }} \
    --otopi-environment="OSETUP_RENAME/forceIgnoreAIAInCA=bool:'True' \
    OVESETUP_CORE/engineStop=bool:'True' \
    OSETUP_RENAME/confirmForceOverwrite=bool:'False'"
  when: grep_diff.stdout != ""
  # ^ i.e skip when engine-name is already at the state we want it to be
  tags:
    - skip_ansible_lint

# this is optional and is to be commented out if your systems use the DNS
# to get the hostname, if not let it remain
- name: Changing the system host name to reflect the new engine-name
  # command: hostnamectl set-hostname {{ ovirt_engine_rename_new_fqdn }}
  command: hostname {{ ovirt_engine_rename_new_fqdn }}
  tags:
    - skip_ansible_lint

- name: Checking if the engine-rename is successful
  command: grep -R --include \*.conf {{ ovirt_engine_rename_new_fqdn }} /etc/ovirt-engine
  changed_when: False
  register: final_check

- name: Engine rename successful or not?
  command: echo Engine Rename successful
  changed_when: False
  when: final_check.rc == 0

- name: check health status of page
  uri:
    url: "http://{{ ovirt_engine_rename_new_fqdn }}/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page is success
