---
# tasks file for ovirt-engine-install-packages
- name: yum install {{ovirt_engine_type}} engine
  yum:
    name: "{{ovirt_engine_type}}"
    state: installed
    update_cache: yes

- name: yum install install {{ovirt_engine_type}} dwh
  yum:
    name: "{{ovirt_engine_type}}-dwh"
    state: present
  when: (ovirt_engine_dwh == True) and (ovirt_engine_version < 4)
